### ISSUE TITLE
An error occurred when the number of spaces is negative

### ISSUE THREAD

**Issue by funnysyc** [ricky8955555/Ricky8955555.CoolQ#2]
**Expected behavior:**
The bot ignores the command when the given arguments are invalid.

**Actual behavior:**
The command gets processed and occurs an error. Stack trace:

```
System.ArgumentOutOfRangeException: “count”必须为非负值。
参数名: count
   在 System.String.CtorCharCount(Char c, Int32 count)
   在 Ricky8955555.CoolQ.Features.SpacingCustomCommand.Invoking(MessageReceivedEventArgs e, PlainText spaceNumberText, ComplexMessage elements)
   在 Ricky8955555.CoolQ.Command`1.Invoke(MessageReceivedEventArgs e)
   在 Ricky8955555.CoolQ.AppBase.FeatureInvoker(MessageReceivedEventArgs e)
   在 Ricky8955555.CoolQ.App.Run(MessageReceivedEventArgs e)
   在 Ricky8955555.CoolQ.Main.MessageReceived(Object sender, MessageReceivedEventArgs e)
```
**Detailed description:**
The sign of `spaceNumber` is not checked in `Ricky8955555.CoolQ.Features.SpacingCustomCommand`.

**Possible solution:**
Add another condition to
https://github.com/ricky8955555/Ricky8955555.CoolQ/blob/c9cd9851c64b4e3d9af6112515a59557d142adbb/Ricky8955555.CoolQ/Features/SpacingCustomCommand.cs#L22

```cs
if (plainText.Count() == elements.Count && int.TryParse(spaceNumberText, out int spaceNumber) && spaceNumber >= 0) 
```

**Steps to reproduce:**
1. Send `/space -42 foo` to the bot.

**Environment:**
The official bot hosted by @ricky8955555 with mirai.

**Comment by ricky8955555** [comment]
Thanks for your issue, I will fix it later.
